// Code generated by "shoot new -getset -sign=@ -file=address.go"; DO NOT EDIT. (v0.7.7)

package vo

// NewAddress constructs a new instance of type Address
func NewAddress(province string, city string, street string, zipCode string) *Address {
	return &Address{
		province: province,
		city:     city,
		street:   street,
		zipCode:  zipCode,
	}
}

// Province gets the value of field province
func (a *Address) Province() string {
	return a.province
}

// City gets the value of field city
func (a *Address) City() string {
	return a.city
}

// Street gets the value of field street
func (a *Address) Street() string {
	return a.street
}

// ZipCode gets the value of field zipCode
func (a *Address) ZipCode() string {
	return a.zipCode
}

// AddressGetter is read-only interface for Address type
type AddressGetter interface {
	Province() string
	City() string
	Street() string
	ZipCode() string
}

// ShootNew exists solely to fulfill the NewShooter interface contract
func (a Address) ShootNew() { /*noop*/ }
